# Generated by Django 5.0.1 on 2024-02-15 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_rename_id_delete_product_is_delete_productvisit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='id_delete',
            new_name='is_delete',
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='ip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_module.product', verbose_name='محصول'),
        ),
        migrations.AlterField(
            model_name='productvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='آی پی کاربر'),
        ),
    ]
