# Generated by Django 4.2.8 on 2024-01-15 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 1, 15), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
